image: gitpod/workspace-full

tasks:
  - name: Setup Laravel + DynamoDB
    init: |
      cd V1/laravel_app

      composer install
      npm install

      cp .env.example .env
      php artisan key:generate

      echo "AWS_ACCESS_KEY_ID=fake" >> .env
      echo "AWS_SECRET_ACCESS_KEY=fake" >> .env
      echo "AWS_DEFAULT_REGION=us-east-1" >> .env
      echo "DYNAMODB_ENDPOINT=http://localhost:8000" >> .env
      echo "DYNAMODB_TABLE=MiMercado" >> .env

      php artisan config:clear

      docker run -d -p 8000:8000 amazon/dynamodb-local

      sleep 5

      php artisan migrate
      php artisan mercado:seed-demo

    command: |
      cd V1/laravel_app
      php artisan serve --host=0.0.0.0 --port=8000

ports:
  - port: 8000
    onOpen: open-preview